### ISSUE TITLE
关闭下载了么。。

### ISSUE THREAD

**Issue by Leohb** [zstackio/zstack#1111]
![image](https://cloud.githubusercontent.com/assets/24680667/26231204/84043ee8-3c80-11e7-9d76-6aa05cef1a2f.png)

之前下载卡在81%.............

**Comment by AlanJager** [comment]
@Leohb 新的下载地址到http://www.zstack.io查看

**Comment by Leohb** [comment]
@AlanJager 
好的，之前加群问过了，不过还是谢谢！
