### ISSUE TITLE
oom exception,so if this account login zstack1 node,and access zstack2,3,4,5....... node ,now this session will be stored in sessions(HashMap)  on many nodes , but expired colletor  can only remove zstack1 or zstack2, and other nodes keep holding this session in memory, it's  potential oom exception 

### ISSUE THREAD

**Issue by yuhaqiang123** [zstackio/zstack#1244]
https://github.com/zstackio/zstack/blob/91b11ebbcd912150a31b3f2d275adc121fe92622/identity/src/main/java/org/zstack/identity/AccountManagerImpl.java#L1044

**Comment by zstackorg** [comment]
Begining at 2.5.0, the session logic has been moved to Session.java. Please
check out the latest master code and see if the issue you mentioned is
still here.
If it is, please post a detailed description of this issue

**Comment by AlanJager** [comment]
Thanks for your reporting, it will be fixed in recent release version.

**Comment by live4thee** [comment]
Close issue since this issue have been fixed since long.
