### ISSUE TITLE
Is Ceph Jewel version compatible with existed CentOS 7.2 based ZStack?

### ISSUE THREAD

**Issue by mchtech** [zstackio/zstack#1245]
According to [http://docs.ceph.com/docs/master/releases/schedule/](url) , Ceph hammer has been EOL for more than one year. CentOS 7.4 based ISO provides a Jewel version repo, which provides more useful functionality and performance improvements. 
If we upgrade ceph nodes, which are also compute nodes and being used by zstack primary storage, **from Hammer to Jewel** version by the method that provided by ceph official documents, will we encounter any compatibility problems (e.g. cephx) ?

**Comment by zstackorg** [comment]
ZStack has moved to Centos7.4 base for a while. Cephx is supported (you
will see the checkbox enabling cephx when adding primary storage), so I
don't think there will be compatibility issues

**Comment by mchtech** [comment]
We have upgraded Ceph from Hammer to Jewel for 9 months. During the upgrade process, we only encountered a very small number of problems, because we have verified the solution many time on test environment. This is the script that we used for upgrading.
This script can only be used as a reference, because each Ceph environment and architecture may be different. 
 
我们已经将Ceph从Hammer升级到Jewel 9个月了，由于先前在测试环境中验证升级了很多次，所以升级过程中只遇到了少量问题。下面的脚本是升级过程中使用的。
这个脚本只能用作参考，因为每个Ceph环境和架构可能是不同的。


```
#!/bin/bash

// Upgrade
yum -y install centos-release-ceph-jewel
sed -i "s/mirror.centos.org/mirrors.aliyun.com/g" /etc/yum.repos.d/CentOS-Ceph-Jewel.repo
yum -y install ceph

ceph osd set noout

// MON : upgrade one by one
chown -R ceph:ceph /var/lib/ceph
chown -R ceph:ceph /var/run/ceph
systemctl stop $(systemctl | grep ceph-mon | grep running|awk '{print $1}')
sleep 1
systemctl start ceph-mon@$(hostname)
systemctl enable ceph-mon@$(hostname)

// OSD : upgrade one by one
osdnums=$(ls /var/lib/ceph/osd/|sed 's/ceph-//g')
if [[ ! -z $osdnums ]];then
    for i in $osdnums;do
        srv=$(systemctl |grep "ceph-osd\.$i"|grep running|awk '{print $1}')
        if [[ ! -z $srv ]];then
            systemctl stop $srv
            echo "set permissions"
            chown -R ceph:ceph /var/lib/ceph
            chown -R ceph:ceph /var/run/ceph
            echo "end set permissions"
            sdx=$(readlink -f /var/lib/ceph/osd/ceph-$i/journal | sed "s/[0-9]//g")
            if [[ ! -z $sdx ]];then
                chown ceph:ceph ${sdx} ${sdx}1 ${sdx}2
                ceph osd down $i
                sleep 2
                systemctl start ceph-osd@$i
                systemctl enable ceph-osd@$i
                cnt=1
                while [ $cnt -gt 0 ];do
                    sleep 2
                    ceph osd tree
                    cnt1=$(ceph osd tree | grep down | wc -l)
                    cnt2=$(ceph -s | grep -E "activating|degraded|undersize|recove|stale|scrub" | wc -l)
                    cnt=$(($cnt1+$cnt2))
                    echo "wait $cnt"
                done
            else
                echo "bug2"
            fi
        else
            echo "bug1"
        fi
    done
else
    echo "bug0"
fi

chown -R ceph:ceph /var/lib/ceph
chown -R ceph:ceph /var/run/ceph

# After upgrade
# n1
ceph osd set require_jewel_osds
# n2
ceph osd set sortbitwise
# n3
ceph osd crush tunables optimal
ceph osd unset noout
```

⚠Before running n1, n2, n3, we must entrue that all VMs on physical servers have been restarted by "shut down and start" or migrated to other physical servers(use ZStack) so as to force QEMU to use new Ceph client library. Otherwise, Vms will stuck. (n1/n2/n3: I forget which command will lead to this issue. It should be n3)

需要注意的是，在运行n1/n2/n3前（大概率是n3，时间太久了记不清了），所有的虚拟机都应该关机再开机，或者在管理中将虚拟机迁移到其它主机上，这样qemu才会使用新升级的ceph客户端库，否则虚拟机会卡住。
