### ISSUE TITLE
重连物理机非常慢

### ISSUE THREAD

**Issue by lly835** [zstackio/zstack#1248]
我在物理机上使用镜像安装的ZStack，硬件设施里添加的物理机就是本机，ip是192.168.1.105
现在有2个问题
1. 每次重启物理机，“就绪状态”都是“重连”，等了5分钟还是如此
2. 我选择重新连接物理机，要等很久，大概3分钟。有时还提示连接失败。我在内网电脑上ssh 192.168.1.105都是非常快的。

你需要什么日志才能看出问题，我可以提供。

**Comment by live4thee** [comment]
提供：

- ZStack版本号，Qemu/libvirt/centos 版本
- /usr/local/zstack/apache-tomcat/logs/management-server.log
- 192.168.1.105 的 /var/log/zstack/zstack-kvmagent.log
- 物理机在 ZStack 的 uuid
- 如果可以，192.168.1.105 上的 iptables-save 记录。

**Comment by live4thee** [comment]
没有日志，没有其他用户报告此问题。
