### ISSUE TITLE
zstack3.1.1 启动时读取配置文件出错

### ISSUE THREAD

**Issue by leinuoa** [zstackio/zstack#1252]
[root@swarm-node-1 classes]# zstack-ctl start
Starting ZStack management node, it may take a few minutes...
ERROR: [Errno 13] Permission denied: '/usr/local/zstack/apache-tomcat/webapps/zstack/WEB-INF/classes/zstack.properties'
property must be in format of "key=value", no space before and after "="

配置文件中所有“=”两边没有空格，还一直报这个错~

**Comment by leinuoa** [comment]
![image](https://user-images.githubusercontent.com/8090559/57843890-9add3700-7801-11e9-9de6-8de048143116.png)

**Comment by leinuoa** [comment]
配置文件几乎都是默认配置，因为在使用过程中，apache-tomcat-7.0.35文件无故丢失，于是新装了apache-tomcat-8.5.35来部署本地备份的zstack.war,启动时便报此错~

**Comment by AlanJager** [comment]
@leinuoa 最好再给一下
`ls -l /usr/local/zstack/apache-tomcat/webapps/zstack/WEB-INF/classes/zstack.properties`
的结果，看配置文件的内容应该没什么问题
以及 
`ls -l /usr/local/zstack/apache-tomcat/`
的结果，如果是替换的apache-tomcat，很可能是没有把所有者修改成zstack
`lrwxrwxrwx 1 zstack zstack 20 9月   4 2017 /usr/local/zstack/apache-tomcat`

**Comment by leinuoa** [comment]
@AlanJager 非常感谢，极有可能是授权用户的问题，修改了之后依旧不能通过zstack-ctl start 来启动，暂时直接运行tomcat start.sh，以及zstack-ctl start_ui 可以成功启动~

**Comment by AlanJager** [comment]
> @AlanJager 非常感谢，极有可能是授权用户的问题，修改了之后依旧不能通过zstack-ctl start 来启动，暂时直接运行tomcat start.sh，以及zstack-ctl start_ui 可以成功启动~

好的，你可以试试 `chown -R zstack:zstack /usr/local/zstack/apache-tomcat/` 保证整个目录的权限也许能够彻底解决你的问题
