### ISSUE TITLE
为什么readme里面的超链接都404了

### ISSUE THREAD

**Issue by tangguochang** [zstackio/zstack#1261]
想了解下这个项目的整体情况，哪里有资料看呢？

**Comment by live4thee** [comment]
@tangguochang https://www.zstack.io/ 研发类参考：“帮助与支持” 栏目，非研发类：“了解产品”。

**Comment by tangguochang** [comment]
> @tangguochang https://www.zstack.io/ 研发类参考：“帮助与支持” 栏目，非研发类：“了解产品”。

谢谢~

**Comment by live4thee** [comment]
@tangguochang 链接其实也[修复](https://github.com/zstackio/zstack/commit/35c49777659f845d9f1a5e561f123cb085a885b1)了，多谢关注。
