### ISSUE TITLE
Where's the lastest release distribution?

### ISSUE THREAD

**Issue by lshmouse** [zstackio/zstack#1267]
There is no release distribution after 3.1.3_release(Dec 17, 2018). Where's the lastest release distribution? Is there any release plan? Thanks~

Will the opensource version of zstack be long-term supported? Thanks

**Comment by live4thee** [comment]
@lshmouse We've moved our focus to https://www.zstack.io and you can find the latest release at https://www.zstack.io/product/product_download/

The opensource version is surely supported as you can see that we have regular commit activities. ;-)
https://github.com/zstackio/zstack/graphs/commit-activity

**Comment by lshmouse** [comment]
@live4thee Thanks for your quick reply. 

The IOS distribution is too complex for us. We want to build the source code from a release and test it. Maybe do some improvement and contribute to the community.   But there is no recent release tag or distribution there? Any release branch is recommanded? Thanks

**Comment by live4thee** [comment]
@lshmouse check "branches".  We have branches for each releases.  Our latest release branch is 3.8.4

**Comment by lshmouse** [comment]
@live4thee OK. Thanks very much~
