### ISSUE TITLE
Restore snapshot wording

### ISSUE THREAD

**Issue by Opswatch** [zstackio/zstack#1270]
Hi 

When restoring a snapshot on the english version of the ui the following comes up:
![Screenshot_2020-05-26 Userops Cloud](https://user-images.githubusercontent.com/15094745/82913772-b7e03600-9f3c-11ea-9c72-029859baef43.png)

Instead of "I knew" a more appropriate translation would probably be "I acknowledge"

**Comment by AlanJager** [comment]
@Opswatch 
Thank you for your advice, we will reply to you as soon as possible.

**Comment by Opswatch** [comment]
Fixed on 4.0 closing this.
