### ISSUE TITLE
添加vCenter服务器，报错没有发现相应集群的计算资源 zstack

### ISSUE THREAD

**Issue by hexmiao** [zstackio/zstack#1274]
vCenter版本6.7

**Comment by hexmiao** [comment]
org.zstack.header.errorcode.OperationFailureException: {"code":"SYS.1006","description":"An operation failed","details":"未找到集群资源","elaboration":"错误信息: 没有发现相应集群的计算资源。","messages":{"code":"1001","message_cn":"没有发现相应集群的计算资源。","message_en":"No clustered compute resource found.","source":"zstack","distance":0.0,"method":"regex"},"cost":"0ms"}

**Comment by huyouba1** [comment]
没有发现相应集群的计算资源。
org.zstack.header.errorcode.OperationFailureException: {"code":"SYS.1006","description":"An operation failed","details":"未找到集群资源","elaboration":"错误信息: 没有发现相应集群的计算资源。","messages":{"code":"1001","message_cn":"没有发现相应集群的计算资源。","message_en":"No clustered compute resource found.","source":"zstack","distance":0.0,"method":"regex"},"cost":"0ms"}
返回:{
  "error": {
    "code": "SYS.1006",
    "description": "An operation failed",
    "details": "org.zstack.header.errorcode.OperationFailureException: {\"code\":\"SYS.1006\",\"description\":\"An operation failed\",\"details\":\"未找到集群资源\",\"elaboration\":\"错误信息: 没有发现相应集群的计算资源。\",\"messages\":{\"code\":\"1001\",\"message_cn\":\"没有发现相应集群的计算资源。\",\"message_en\":\"No clustered compute resource found.\",\"source\":\"zstack\",\"distance\":0.0,\"method\":\"regex\"},\"cost\":\"0ms\"}",
    "cost": "0ms"
  },
  "jobUuid": "1db1188076143efaaa8124bf1f7db9c4",
  "success": false,
  "sessionUuid": "f577d7ecf2dc40c7afda73f1998b7796"
}
