### ISSUE TITLE
Request for security contact

### ISSUE THREAD

**Issue by pwntester** [zstackio/zstack#1281]
The [GitHub Security Lab](https://securitylab.github.com/) team has found a potential vulnerability in ZStack. Please create a draft [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me (pwntester) to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

If you prefer to contact us by email, please reach out to securitylab@github.com with reference to GHSL-2021-065.

Kind regards,
Alvaro Muñoz
GitHub Security Lab

**Comment by MatheMatrix** [comment]
@pwntester hi Alvaro, thanks for your work on vulnerability in ZStack, we create a draft Security Advisory at https://github.com/zstackio/zstack/security/advisories/GHSA-6xgq-7rqg-x3q5 

Best regards,
Wei Wang

**Comment by pwntester** [comment]
Thanks!
