### ISSUE TITLE
Request for security contact

### ISSUE THREAD

**Issue by Litch1-v** [zstackio/zstack#1285]
Hi
I am Litch1 from the security team of Alibaba Cloud,we have found a potential vulnerability in ZStack. 
Please create a draft Security Advisory and invite me to further disclose and discuss the vulnerability details and potential fix. 
refer to #1281 
Thanks!

**Comment by AlanJager** [comment]
Hello @Litch1-v thanks for your work on vulnerability in ZStack. Draft Security Advisory have been created https://github.com/zstackio/zstack/security/advisories/GHSA-99wx-p6w8-3hg8.
