### ISSUE TITLE
Zstack 怎么集成 glusterfs

### ISSUE THREAD

**Issue by xuanyuanaosheng** [zstackio/zstack#1299]
目前有HITACHI的VSP SAN存储，想问下怎么通过Shared Mount Point主存储：采用共享文件系统存储为主存储，支持SAN存储，格式化为GlusterFS 来进行集成？

https://www.zstack.io/help/product_manuals/maintenance_manual/v3/9.4.html#chapter-9-4-3-Shared-Mount-Point

**Comment by AlanJager** [comment]
@xuanyuanaosheng 你好

如果需要试用SharedMountPoint，按照文档里的步骤实际上是需要在所有host上面先把存储挂好的，至于格式化挂载的动作都是用户完成的，可以具体分享一下的你说的集成问题是目前哪个环节有问题吗

**Comment by xuanyuanaosheng** [comment]
@AlanJager  是我没有理解，也没有在 cloudstack 的官方文档中找到 **使用Shared Mount Point作为主存储，采用共享文件系统存储为主存储，支持SAN存储，格式化为GlusterFS**.  这个具体怎么做

我们使用的SAN存储是 HITACHI VSP，现在可以做到在VSP上分出来一个 5T 的存储挂在两个 zstack的计算节点上。

zswork001
```
# multipath -ll
mpatham (360060e801262eb00504062eb000000ea) dm-26 HITACHI,OPEN-V
size=5.0T features='0' hwhandler='0' wp=rw
`-+- policy='service-time 0' prio=1 status=active
  |- 1:0:8:1  sdbd 67:112 active ready running
  `- 2:0:10:1 sdbe 67:128 active ready running


# fdisk -l
Disk /dev/sda: 894.2 GiB, 960163569664 bytes, 1875319472 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes
Disklabel type: gpt
Disk identifier: ADE9C21E-CBF8-4F90-A4B4-F2EFC77C1AEA

Device       Start       End   Sectors  Size Type
/dev/sda1     2048   2099199   2097152    1G EFI System
/dev/sda2  2099200   4196351   2097152    1G Linux filesystem
/dev/sda3  4196352 570443775 566247424  270G Linux LVM


Disk /dev/mapper/ol-root: 50 GiB, 53687091200 bytes, 104857600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-swap: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-opt: 50 GiB, 53687091200 bytes, 104857600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-var: 50 GiB, 53687091200 bytes, 104857600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-home: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-image: 100 GiB, 107374182400 bytes, 209715200 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/sdbd: 5 TiB, 5497558138880 bytes, 10737418240 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 65536 bytes / 65536 bytes


Disk /dev/sdbe: 5 TiB, 5497558138880 bytes, 10737418240 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 65536 bytes / 65536 bytes


Disk /dev/mapper/mpatham: 5 TiB, 5497558138880 bytes, 10737418240 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 65536 bytes / 65536 bytes


# lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda            8:0    0 894.2G  0 disk  
├─sda1         8:1    0     1G  0 part  /boot/efi
├─sda2         8:2    0     1G  0 part  /boot
└─sda3         8:3    0   270G  0 part  
  ├─ol-root  252:0    0    50G  0 lvm   /
  ├─ol-swap  252:1    0    10G  0 lvm   [SWAP]
  ├─ol-opt   252:2    0    50G  0 lvm   /opt
  ├─ol-var   252:3    0    50G  0 lvm   /var
  ├─ol-home  252:4    0    10G  0 lvm   /home
  └─ol-image 252:5    0   100G  0 lvm   /image
sdbd          67:112  0     5T  0 disk  
└─mpatham    252:26   0     5T  0 mpath 
sdbe          67:128  0     5T  0 disk  
└─mpatham    252:26   0     5T  0 mpath
```

zswork002
```
# multipath -ll
mpatham (360060e801262eb00504062eb000000ea) dm-50 HITACHI,OPEN-V
size=5.0T features='0' hwhandler='0' wp=rw
`-+- policy='service-time 0' prio=1 status=active
  |- 1:0:8:1  sdbd 67:112 active ready running
  `- 2:0:10:1 sdbe 67:128 active ready running

# fdisk -l
Disk /dev/sda: 894.2 GiB, 960163569664 bytes, 1875319472 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes
Disklabel type: gpt
Disk identifier: DB76AE3B-E647-4D38-9BF8-630958F8F240

Device       Start       End   Sectors  Size Type
/dev/sda1     2048   2099199   2097152    1G EFI System
/dev/sda2  2099200   4196351   2097152    1G Linux filesystem
/dev/sda3  4196352 591415295 587218944  280G Linux LVM


Disk /dev/mapper/ol-root: 50 GiB, 53687091200 bytes, 104857600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-swap: 10 GiB, 10737418240 bytes, 20971520 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-opt: 50 GiB, 53687091200 bytes, 104857600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-home: 20 GiB, 21474836480 bytes, 41943040 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-var: 50 GiB, 53687091200 bytes, 104857600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/mapper/ol-image: 100 GiB, 107374182400 bytes, 209715200 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 262144 bytes / 262144 bytes


Disk /dev/sdbd: 5 TiB, 5497558138880 bytes, 10737418240 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 65536 bytes / 65536 bytes


Disk /dev/sdbe: 5 TiB, 5497558138880 bytes, 10737418240 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 65536 bytes / 65536 bytes


Disk /dev/mapper/mpatham: 5 TiB, 5497558138880 bytes, 10737418240 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 65536 bytes / 65536 bytes

# lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda            8:0    0 894.2G  0 disk  
├─sda1         8:1    0     1G  0 part  /boot/efi
├─sda2         8:2    0     1G  0 part  /boot
└─sda3         8:3    0   280G  0 part  
  ├─ol-root  252:0    0    50G  0 lvm   /
  ├─ol-swap  252:1    0    10G  0 lvm   [SWAP]
  ├─ol-opt   252:2    0    50G  0 lvm   /opt
  ├─ol-home  252:3    0    20G  0 lvm   /home
  ├─ol-var   252:4    0    50G  0 lvm   /var
  └─ol-image 252:5    0   100G  0 lvm   /image
sdbd          67:112  0     5T  0 disk  
└─mpatham    252:50   0     5T  0 mpath 
sdbe          67:128  0     5T  0 disk  
└─mpatham    252:50   0     5T  0 mpath

```

因为分配出来的 5T 的存储就是SAN存储上的同一块盘，请问下怎么格式化为glusterfs ，然后在zstack的web端使用Shared Mount Point ？

**Comment by AlanJager** [comment]
@xuanyuanaosheng 这两个步骤并不冲突，你只需要正常的初始化好glusterfs之后通过mount的方式在host上挂载这个存储到相同的目录就行，ZStack实际上要求的是有同一个目录，mount的时候都指定你的glusterfs就行

**Comment by xuanyuanaosheng** [comment]
@AlanJager  好像大概理解了，但是这样其实是不是有比较大的性能损耗？

对于SAN的存储来说，因为SAN存储能直接支持把相同的存储分配到zstack的计算节点上，没必要再虚拟一层gluster的文件系统了吧，再请教下，有SAN存储的情况下，使用zstack的最佳实践是啥？

**Comment by AlanJager** [comment]
@xuanyuanaosheng 那感觉你可以看一下 https://www.zstack.io/help/product_manuals/maintenance_manual/v3/9.4.html#chapter-9-4-5-Shared-Block 我们提供的shared block存储，直接通过lvm管理，少了一层文件系统，能解决你说的性能损耗问题，也是目前我们提供的一个更好的方式

如果你还是需要使用文件系统的话，始终还是绕不开这个问题

**Comment by AlanJager** [comment]
> @AlanJager 好的，感谢。
> 
> 1. 顺便问一下，使用的开源版本怎么通过命令升级成企业版本？我想测试下企业版本的功能。
> 2. 如果升级成企业版本，还能会滚成开源版本么？

有两个方式，
免费方式：
1. 确认当前环境中物理机只有一台，如果多余一台需要减少到一台
2. 执行命令 `zstack-ctl install_license --license /var/lib/zstack/license/zstack_trial_license`
3. 在界面上更新license或者在命令行执行 `zstack-cli` 进入命令行后 调用 `ReloadLicense` 更新

付费方式：
https://www.zstack.io/aboutus/contact_us/ 可以通过商务联系获取付费的企业版本

升级成企业版本之后通过许可证管理，所以除非license过期，否则都会是企业版

**Comment by xuanyuanaosheng** [comment]
@AlanJager  请问有初始化需要配置哪些的文档么？我这边初始化引导不小心跳过去了，然后就找不到了。现在无法新建虚拟机，不知道中间哪些没配置。

1. 创建区域
![image](https://user-images.githubusercontent.com/4197714/172977892-5ecb06e5-a49d-4e0e-b3b7-a587845cbab3.png)


2.  创建集群

![image](https://user-images.githubusercontent.com/4197714/172977892-5ecb06e5-a49d-4e0e-b3b7-a587845cbab3.png)

3.   集群中包含的

![image](https://user-images.githubusercontent.com/4197714/172978003-4e0ccb46-6524-4760-962f-5153d1a3d062.png)

4.  节点

![image](https://user-images.githubusercontent.com/4197714/172978053-d576299b-6011-4b96-98ec-c8d10957b06e.png)

5.   创建了2层网络

![image](https://user-images.githubusercontent.com/4197714/172978384-b46a290d-5c85-4b07-8363-3b556f18061e.png)

6.  创建了公有三层网络

![image](https://user-images.githubusercontent.com/4197714/172978491-5b0d43d4-e6e9-4530-84b6-d2e7a4617907.png)


7.  创建了管理网络

![image](https://user-images.githubusercontent.com/4197714/172978555-b41fa9c6-048a-4f24-8501-0684402469b5.png)

已经完成以上步骤，在创建云主机的时候无法选择三层网络：

![image](https://user-images.githubusercontent.com/4197714/172978689-6399d2a7-e875-4981-84a7-48413bebe8fa.png)

能麻烦问下是少了什么么？



(PS:  刚开始有个创建引导，我一不小心跳过去了，请问这个有相关的文档么？)

**Comment by MatheMatrix** [comment]
> @AlanJager 请问有初始化需要配置哪些的文档么？我这边初始化引导不小心跳过去了，然后就找不到了。现在无法新建虚拟机，不知道中间哪些没配置。
> 
> 1. 创建区域
>    ![image](https://user-images.githubusercontent.com/4197714/172977892-5ecb06e5-a49d-4e0e-b3b7-a587845cbab3.png)
> 2. 创建集群
> 
> ![image](https://user-images.githubusercontent.com/4197714/172977892-5ecb06e5-a49d-4e0e-b3b7-a587845cbab3.png)
> 
> 3. 集群中包含的
> 
> ![image](https://user-images.githubusercontent.com/4197714/172978003-4e0ccb46-6524-4760-962f-5153d1a3d062.png)
> 
> 4. 节点
> 
> ![image](https://user-images.githubusercontent.com/4197714/172978053-d576299b-6011-4b96-98ec-c8d10957b06e.png)
> 
> 5. 创建了2层网络
> 
> ![image](https://user-images.githubusercontent.com/4197714/172978384-b46a290d-5c85-4b07-8363-3b556f18061e.png)
> 
> 6. 创建了公有三层网络
> 
> ![image](https://user-images.githubusercontent.com/4197714/172978491-5b0d43d4-e6e9-4530-84b6-d2e7a4617907.png)
> 
> 7. 创建了管理网络
> 
> ![image](https://user-images.githubusercontent.com/4197714/172978555-b41fa9c6-048a-4f24-8501-0684402469b5.png)
> 
> 已经完成以上步骤，在创建云主机的时候无法选择三层网络：
> 
> ![image](https://user-images.githubusercontent.com/4197714/172978689-6399d2a7-e875-4981-84a7-48413bebe8fa.png)
> 
> 能麻烦问下是少了什么么？
> 
> (PS: 刚开始有个创建引导，我一不小心跳过去了，请问这个有相关的文档么？)

是不是公有网络所在的二层网络没有绑定集群？

如果想再走一遍创建引导，只要把 zone 删掉就会触发

**Comment by xuanyuanaosheng** [comment]
@MatheMatrix  @AlanJager   OK，那我测试一下。  希望创建 Zone的时候还是能调用一下这个引导。

**Comment by xuanyuanaosheng** [comment]
我会关闭这个issue，有新的issue, 我会从新提出，感谢各位的耐心解答。
