### ISSUE TITLE
Zstack AddCephPrimaryStorageAction Failed

### ISSUE THREAD

**Issue by xuanyuanaosheng** [zstackio/zstack#1300]
Zstack 所在节点的IP: 10.26.246.18
Zstack的的版本：4.2.20

Ceph的mon节点的IP为：10.29.44.1，10.29.44.2，10.29.44.3

Ceph的版本：ceph version 15.2.12 
```
# ceph --version
ceph version 15.2.12 (ce065eabfa5ce81323b009786bdf5bb03127cbe1) octopus (stable)
```

在zstack节点上可以使用zstack账号登陆对应的ceph节点，且zstack账号在ceph节点上有 sudo 权限。
```
[root@wxxxzstack001 ~]# ping 10.29.44.1
PING 10.29.44.1 (10.29.44.1) 56(84) bytes of data.
64 bytes from 10.29.44.1: icmp_seq=1 ttl=61 time=0.315 ms
^C
--- 10.29.44.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.315/0.315/0.315/0.000 ms
[root@wxxxzstack001 ~]# ping 10.29.44.2
PING 10.29.44.2 (10.29.44.2) 56(84) bytes of data.
64 bytes from 10.29.44.2: icmp_seq=1 ttl=61 time=0.340 ms
^C
--- 10.29.44.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.340/0.340/0.340/0.000 ms
[root@wxxxzstack001 ~]# telnet 10.29.44.1 22
Trying 10.29.44.1...
Connected to 10.29.44.1.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.4
^C^C^C^C
Connection closed by foreign host.
[root@wxxxzstack001 ~]# telnet 10.29.44.2 22
Trying 10.29.44.2...
Connected to 10.29.44.2.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.4
^C
Connection closed by foreign host.
```

在web 页面增加Ceph的主存储报错：

![image](https://user-images.githubusercontent.com/4197714/172123500-e410a4cb-d255-42d9-ac04-459e8075b38a.png)

![image](https://user-images.githubusercontent.com/4197714/172123791-2bd0cc54-5795-426b-9f25-43ab5e7810b1.png)

使用的账号为zstack，有sudo权限。

具体报错如下：
```
{
  "执行API结果": "失败",
  "操作时间": "2022-06-06 16:02:54",
  "完成时间": "2022-06-06 16:02:56",
  "API ID": "678dfa1614f24580ac27ded908aabf3a",
  "请求": {
    "name": "HCCWH-Ceph-Prod",
    "description": "",
    "zoneUuid": "44d65cbb12e04f54be165ae9ff5e61df",
    "monUrls": [
      "zstack:zstack@123@10.29.44.1:22",
      "zstack:zstack@123@10.29.44.2:22"
    ],
    "systemTags": [
      "primaryStorage::gateway::cidr::10.29.44.0/24"
    ]
  },
  "错误返回": {
    "error": {
      "code": "SYS.1006",
      "description": "An operation failed",
      "details": "无法连接到ceph主存储[uuid:a6c9743fead8465c9d2758c40e1ebff5]。所有监控节点均连接失败。错误是[{\"code\":\"SYS.1000\",\"description\":\"An internal error happened in system\",\"details\":\"\",\"location\":\"CephPrimaryStorageMonBase.java: check-tools (location:1/5)\",\"cost\":\"0ms\"},{\"code\":\"SYS.1000\",\"description\":\"An internal error happened in system\",\"details\":\"\",\"location\":\"CephPrimaryStorageMonBase.java: check-tools (location:1/5)\",\"cost\":\"0ms\"}]",
      "location": "CephPrimaryStorageBase.java: connect-monitor (location:1/4)",
      "cost": "0ms"
    }
  }
}
```

**Comment by AlanJager** [comment]
@xuanyuanaosheng 看出错的地方时check-tools这个flow，参考开源代码，里面会检查ceph和rbd命令

可以用`which ceph`和`which rbd`来确认工具的情况，再这之后，会额外检查一下`ceph health`的返回结果，期望的结果是return code为0，并且返回的状态不是“HEALTH_ERROR”

当然我们也希望你能提供详细的ZStack版本以及Ceph版本的信息，以及通过在management-server.log中grep “ 678dfa1614f24580ac27ded908aabf3a” 这个api相关的操作提供更详细的日志，便于问题的进一步分析

**Comment by AlanJager** [comment]
> @AlanJager 按照您的要求：
> 
> 在ceph上执行相关命令的结果：
> 
> ```
> [root@whxxxceph001 ~]# which ceph
> /bin/ceph
> [root@whxxxceph001 ~]# which rbd
> /bin/rbd
> [root@whxxxceph001 ~]# ceph health
> HEALTH_WARN 3 hosts fail cephadm check; 3 large omap objects; mon whdrcceph001.cn.prod is low on available space
> ```

`ceph health`
执行之后麻烦打印一下
`echo $?`

**Comment by xuanyuanaosheng** [comment]
@AlanJager 我更新了 comment，打印结果是0

**Comment by AlanJager** [comment]
@xuanyuanaosheng 这样看来工具已经是正确的了，如果是部署agent出错说明在执行ansible的时候出现了什么问题，提供一下脱敏（隐藏密码，ip地址等）的 `/var/log/zstack/deploy.log` 来分析一下么？

**Comment by xuanyuanaosheng** [comment]
[deploy.log](https://github.com/zstackio/zstack/files/8843072/deploy.log)

请您查收

**Comment by AlanJager** [comment]
查看日志

```
2022-05-31 18:03:27,616 - DEBUG - {'dark': {}, 'contacted': {'10.29.44.1': {'invocation': {'module_name': 'setup', 'module_complex_args': {}, 'module_args': u'filter=ansible_distribution*'}, 'verbose_override': True, 'changed': False, 'ansible_facts': {'ansible_distribution_version': '7.9', 'ansible_distribution': 'OracleLinux', 'ansible_distribution_release': 'NA', 'ansible_distribution_major_version': '7'}}}}
```

发现ansible_distribution是OracleLinux，目前我们支持的`RPM_BASED_OS`和`DEB_BASED_OS`分别是
```
RPM_BASED_OS = ["centos", "redhat", "alibaba", "kylin10"]
DEB_BASED_OS = ["ubuntu", "kylin4.0.2", "uos", "debian", "uniontech"]
```
因此部署agent的时候会报错提示：
```
2022-05-31 18:03:28,241 - ERROR - ERROR: Unsupported distribution
```

建议使用ISO提供的guest版本，或者通过修改utility代码的方式进行适配开发

**Comment by xuanyuanaosheng** [comment]
1.   看了您的回复，Oracle Linux也是rpm系列的，想问下，在ceph节点上有啥办法能修改一下 ansible_distribution 为 Centos 么？
```
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

2. 不知道使用下面的命令可不可以修复：
sudo PYTHONPATH=/usr/local/zstack/ansible/files/zstacklib timeout 1800 python /usr/local/zstack/ansible/cephp.py -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-8.5.57/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\n \"chrony_servers\": \"10.26.246.18\",\n \"trusted_host\": \"10.26.246.18\",\n \"remote_port\": \"22\",\n \"host_uuid\": \"e421ccc5fc7843aa8e27758f5940e16b\",\n \"zstack_root\": \"/var/lib/zstack\",\n \"remote_user\": \"root\",\n \"remote_pass\": \"*****\",\n \"host\": \"10.29.44.1\",\n \"pip_url\": \"http://10.26.246.18:8080/zstack/static/pypi/simple\",\n \"zstack_repo\": \"\\\"zstack-mn,qemu-kvm-ev-mn,mlnx-ofed-mn\\\"\",\n \"pkg_cephpagent\": \"cephprimarystorage-4.2.0.tar.gz\",\n \"yum_server\": \"10.26.246.18:8080\",\n \"pkg_zstacklib\": \"zstacklib-4.2.0.tar.gz\"\n}'

3.   要是直接使用命令的方式增加ceph的存储，也是会有检查这一步么？

**Comment by AlanJager** [comment]
> 1. 看了您的回复，Oracle Linux也是rpm系列的，想问下，在zstack的节点上有啥办法能修改一下 ansible_distribution 为 Oracle Linux 么？
> 
> ```
> ceph节点上执行命令：
> # cat /etc/redhat-release 
> Red Hat Enterprise Linux Server release 7.9 (Maipo)
> ```
> 
> 2. 不知道使用下面的命令可不可以修复：
> 
> ```
> sudo PYTHONPATH=/usr/local/zstack/ansible/files/zstacklib timeout 1800 python /usr/local/zstack/ansible/cephp.py -i /usr/local/zstack/ansible/hosts --private-key /usr/local/zstack/apache-tomcat-8.5.57/webapps/zstack/WEB-INF/classes/ansible/rsaKeys/id_rsa -e '{\n \"chrony_servers\": \"10.26.246.18\",\n \"trusted_host\": \"10.26.246.18\",\n \"remote_port\": \"22\",\n \"host_uuid\": \"e421ccc5fc7843aa8e27758f5940e16b\",\n \"zstack_root\": \"/var/lib/zstack\",\n \"remote_user\": \"root\",\n \"remote_pass\": \"*****\",\n \"host\": \"10.29.44.1\",\n \"pip_url\": \"http://10.26.246.18:8080/zstack/static/pypi/simple\",\n \"zstack_repo\": \"\\\"zstack-mn,qemu-kvm-ev-mn,mlnx-ofed-mn\\\"\",\n \"pkg_cephpagent\": \"cephprimarystorage-4.2.0.tar.gz\",\n \"yum_server\": \"10.26.246.18:8080\",\n \"pkg_zstacklib\": \"zstacklib-4.2.0.tar.gz\"\n}'
> ```
> 
> 3. 要是直接使用命令的方式增加ceph的存储，也是会有检查这一步么？

1. 
是这样的，ZStack在设计上是通过mn提供的源来下载计算/存储节点依赖的，因此需要通过适配的方式才能够增加OS的支持，直接用命令的情况始终会进入ZStack的deploy逻辑并检查OS类型

如果说要修改ansible_distribution的话需要修改zstack-utility这个开源repo的代码（地址：https://github.com/zstackio/zstack-utility）

执行下面的命令：
```
git grep 'RPM_BASED_OS ='
```
可以看到相关需要改动的内容

```
zstackctl/zstackctl/zstacklib.py:RPM_BASED_OS = ["centos", "redhat", "alibaba", "kylin10"]
zstacklib/ansible/zstacklib.py:RPM_BASED_OS = ["centos", "redhat", "alibaba", "kylin10", "openeuler"]
zstacklib/zstacklib/utils/linux.py:RPM_BASED_OS = ['redhat', 'centos', 'alibaba', 'kylin10']
```
修改代码的好处是便于你后续维护，并且由于我们的代码并没支持Oracle Linux，因此后续使用也会存在潜在的问题

2. 这个改法不行，因为还是通过ansible部署，ansible里面依赖的zstacklib库会限定OS类型
3. 通过命令添加也是类似的，另外ZStack是通过控制面使用的数据库记录硬件资源信息的，所以还是需要通过API添加

如上，可以通过手动执行命令的方式来做debug，最理想的还是可以主动修改code来做这个Host OS的适配

**Comment by xuanyuanaosheng** [comment]
@AlanJager 嗯嗯  了解了，也就是不管是通过API还是命令行，最后底层的执行逻辑都会转到 Ansible 上面，继而进行 ansible_distribution 的检查。

**Comment by xuanyuanaosheng** [comment]
@AlanJager  哦了,我先在我的环境中进行测试

没修改之前的：

```
# grep -ri "RPM_BASED_OS =" ./*
./virtualenv/zstackcli/lib/python2.7/site-packages/ansible/zstacklib.py:RPM_BASED_OS = ["centos", "redhat", "alibaba", "kylin10"]
./virtualenv/zstackcli/lib/python2.7/site-packages/zstacklib/utils/linux.py:RPM_BASED_OS = ['redhat', 'centos', 'alibaba', 'kylin10']
./virtualenv/zstackctl/lib/python2.7/site-packages/zstackctl/zstacklib.py:RPM_BASED_OS = ["centos", "redhat", "alibaba", "kylin10"]
./virtualenv/consoleproxy/lib/python2.7/site-packages/ansible/zstacklib.py:RPM_BASED_OS = ["centos", "redhat", "alibaba", "kylin10"]
./virtualenv/consoleproxy/lib/python2.7/site-packages/zstacklib/utils/linux.py:RPM_BASED_OS = ['redhat', 'centos', 'alibaba', 'kylin10']
./virtualenv/kvm/lib/python2.7/site-packages/ansible/zstacklib.py:RPM_BASED_OS = ["centos", "redhat", "alibaba", "kylin10"]
./virtualenv/kvm/lib/python2.7/site-packages/zstacklib/utils/linux.py:RPM_BASED_OS = ['redhat', 'centos', 'alibaba', 'kylin10']
./virtualenv/sftpbackupstorage/lib/python2.7/site-packages/ansible/zstacklib.py:RPM_BASED_OS = ["centos", "redhat", "alibaba", "kylin10"]
./virtualenv/sftpbackupstorage/lib/python2.7/site-packages/zstacklib/utils/linux.py:RPM_BASED_OS = ['redhat', 'centos', 'alibaba', 'kylin10']
```

修改之后的
```
# grep -ri "RPM_BASED_OS =" ./*
./virtualenv/zstackcli/lib/python2.7/site-packages/ansible/zstacklib.py:RPM_BASED_OS = ["centos", "OracleLinux", "redhat", "alibaba", "kylin10"]
./virtualenv/zstackcli/lib/python2.7/site-packages/zstacklib/utils/linux.py:RPM_BASED_OS = ['redhat', 'OracleLinux', 'centos', 'alibaba', 'kylin10']
./virtualenv/zstackctl/lib/python2.7/site-packages/zstackctl/zstacklib.py:RPM_BASED_OS = ["centos", "OracleLinux", "redhat", "alibaba", "kylin10"]
./virtualenv/consoleproxy/lib/python2.7/site-packages/ansible/zstacklib.py:RPM_BASED_OS = ["centos", "OracleLinux", "redhat", "alibaba", "kylin10"]
./virtualenv/consoleproxy/lib/python2.7/site-packages/zstacklib/utils/linux.py:RPM_BASED_OS = ['redhat', 'OracleLinux', 'centos', 'alibaba', 'kylin10']
./virtualenv/kvm/lib/python2.7/site-packages/ansible/zstacklib.py:RPM_BASED_OS = ["centos", "OracleLinux", "redhat", "alibaba", "kylin10"]
./virtualenv/kvm/lib/python2.7/site-packages/zstacklib/utils/linux.py:RPM_BASED_OS = ['redhat', 'OracleLinux', 'centos', 'alibaba', 'kylin10']
./virtualenv/sftpbackupstorage/lib/python2.7/site-packages/ansible/zstacklib.py:RPM_BASED_OS = ["centos", "OracleLinux", "redhat", "alibaba", "kylin10"]
./virtualenv/sftpbackupstorage/lib/python2.7/site-packages/zstacklib/utils/linux.py:RPM_BASED_OS = ['redhat', 'OracleLinux', 'centos', 'alibaba', 'kylin10']
```

deploy.log的报错依然还是：
```
2022-06-07 10:19:02,992 - ERROR - ERROR: Unsupported distribution
```

**Comment by xuanyuanaosheng** [comment]
@AlanJager  我还想到一个方法，既然Zstack的服务端对Ceph的操作系统进行了检测，我们可以在Ceph的操作系统上进行一些修改，进而达到欺骗Zstack服务端，进而实现cephagent的安装。

**Comment by AlanJager** [comment]
> @AlanJager 我还想到一个方法，既然Zstack的服务端对Ceph的操作系统进行了检测，我们可以在Ceph的操作系统上进行一些修改，进而达到欺骗Zstack服务端，进而实现cephagent的安装。

这样做太tricky了，上面你给出的替换python代码的操作，实际上修改的是已经部署好的agent的代码，对未部署的ceph是没有影响的，以4.4.0版本环境为例，正确的修改方法：

需要注意：以下操作会覆盖相应文件，注意做好备份

用root用户登陆管理节点

找到 `/usr/local/zstack/apache-tomcat-8.5.57/webapps/zstack/WEB-INF/classes/ansible/zstacklib/`

解压 `tar zxvf zstacklib-4.4.0.tar.gz` 并修改你要修改的代码

然后把修改好的内容重新打包 `tar zcvf zstacklib-4.4.0.tar.gz zstacklib-4.4.0/`

新打包好的 `zstacklib-4.4.0.tar.gz`

注意：需要修改所有者为zstack

`chown zstack:zstack zstacklib-4.4.0.tar.gz`

备份部署路径的压缩包：
`mv /usr/local/zstack/ansible/files/zstacklib/zstacklib-4.4.0.tar.gz /usr/local/zstack/ansible/files/zstacklib/zstacklib-4.4.0.tar.gz.backup`

然后将新的包替换到部署路径
`cp /usr/local/zstack/apache-tomcat-8.5.57/webapps/zstack/WEB-INF/classes/ansible/zstacklib/zstacklib-4.4.0.tar.gz /usr/local/zstack/ansible/files/zstacklib/zstacklib-4.4.0.tar.gz`

完成后修改的代码就被替换到运行中的环境里了，此时对host/primary storage/backup storage进行重连/新增操作都会使用这个新的包

**Comment by xuanyuanaosheng** [comment]
搞定，我打算把单子关闭掉。
