### ISSUE TITLE
How do I get the text-mode dashboard back after a restart?

### ISSUE THREAD

**Issue by kcwongigs** [zstackio/zstack#1311]
After installation, in ZStack server, Ctrl-Alt-F1 displays a text-mode dashboard containing the status of various resources. However after I reboot ZStack server, Ctrl-Alt-F1 only shows a login prompt. After I login as root, it is the same console same as Ctrl-Alt-F2. 

Which command do I run to get the text-mode dashboard back?

**Comment by MatheMatrix** [comment]
The text-mode dashboard has been disabled since ZStack Cloud 4.4.10 😢
