### ISSUE TITLE
安全组问题

### ISSUE THREAD

**Issue by gituib** [zstackio/zstack#1316]
版本：社区版4.4.27
你好，麻烦问一下
添加安全组的话没有拒绝和允许的策略可供选择吗？
添加都是默认允许通过，没有拒绝!

**Comment by AlanJager** [comment]
@gituib 请问能不能具体举例你的使用场景？

可以参考官网文档：https://www.zstack.io/help/product_manuals/user_guide/v4/10.4.html#chapter-10-4-1-1-%E6%A6%82%E8%BF%B0

概述的下一节中有这样的内容：

```
新建安全组时，默认配置了两条规则（即：协议类型为ALL的进口规则和出口规则），用于设置组内互通。用户可以删除这两条默认规则，取消组内互通。
```

默认组内是允许互通的，不知道是否是这个问题

**Comment by gituib** [comment]
谢谢  ，
