### ISSUE TITLE
VPC路由器的账号密码能修改吗？

### ISSUE THREAD

**Issue by gituib** [zstackio/zstack#1319]
VPC路由器的账号密码能修改吗,我登录进去用passwd修改没用
![@QUV5GUB`0 BNAN8PD1UIO](https://user-images.githubusercontent.com/35016327/188353277-7f4243af-23b6-47d6-96a1-2dc1f7c50172.png)

**Comment by AlanJager** [comment]
你可以通过如下方法查询你的默认vyos密码

1. 登录zstack-cli
2. QueryGlobalConfig category=virtualRouter name=vrouter.password

**Comment by ruansteve** [comment]
VPC路由器是无状态的，每次重启zstack都会重新配置VPC, 不希望用户修改VPC配置。

**Comment by gituib** [comment]
> 你可以通过如下方法查询你的默认vyos密码
> 
> 1. 登录zstack-cli
> 2. QueryGlobalConfig category=virtualRouter name=vrouter.password

默认密码我知道是多少，但是默认密码是只有小写，会被认定为弱密码

**Comment by MatheMatrix** [comment]
> > 你可以通过如下方法查询你的默认vyos密码
> > 
> > 1. 登录zstack-cli
> > 2. QueryGlobalConfig category=virtualRouter name=vrouter.password
> 
> 默认密码我知道是多少，但是默认密码是只有小写，会被认定为弱密码

把上面 @ruansteve 发的命令，query改成update，就可以修改了，然后重启vpc即可

**Comment by gituib** [comment]
> 谢谢大佬，按这个方法改过来了

**Comment by gituib** [comment]
>
