### ISSUE TITLE
管理页面任务进度卡在99.99%

### ISSUE THREAD

**Issue by PollosD** [zstackio/zstack#1324]
管理页面之前新增物理机的任务进度卡在99.99%，一直显示进行中无法强制停止，这个怎么关掉

**Comment by MatheMatrix** [comment]
你好能收集一下日志通过阿里云盘或者其他方法上传一下么

**Comment by PollosD** [comment]
![1667989924389_DB7DAD53-C16F-4a44-981E-7574F937C4C8](https://user-images.githubusercontent.com/55781685/200807420-5a1cceb5-6348-406f-809e-e01be8bfd197.png)
![1667989902359_1F43C5E0-4A48-4858-9DF5-0FE0AD270FB8](https://user-images.githubusercontent.com/55781685/200807439-4422098d-bc84-4df8-a59e-d3ae4a817360.png)
任务一直在99.99%  点进去里面显示已经失败了 目前来看没什么影响 就是看起来很难受

**Comment by MatheMatrix** [comment]
可以临时通过执行

http://host:port/api/operation/action/cancel?actionId=1ab67630af1f4cb985a083c37e0a754c

host:port 替换成管理节点 IP、端口

然后刷新浏览器再看下

**Comment by MatheMatrix** [comment]
另外能不能截图看下是哪个版本啊

**Comment by PollosD** [comment]
> 另外能不能截图看下是哪个版本啊

好的，谢谢 我试下 版本是社区版4.2.28

**Comment by MatheMatrix** [comment]
> > 另外能不能截图看下是哪个版本啊
> 
> 好的，谢谢 我试下 版本是社区版4.2.28

OK，进度 99% 不返回的问题应该是在 4.3、4.4 解决了
