### ISSUE TITLE
ui失败

### ISSUE THREAD

**Issue by admin-ping** [zstackio/zstack#1337]
服务器意外断电后使用命令“zstack-ctl start_ui”报错：

nginx server config file /usr/local/zstack/zstack-ui/configs/extend.server.nginx.conf
nginx upstream config file /usr/local/zstack/zstack-ui/configs/extend.upstream.nginx.conf
pm2 config file /usr/local/zstack/zstack-ui/configs/extend.ecosystem.config.json
node: relocation error: node: symbol -Emcmp, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
ERROR 1045 (28000): Access denied for user 'zstack_ui'@'localhost' (using password: NO)
node: relocation error: node: symbol -Emcmp, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
 ... -node: relocation error: node: symbol -Emcmp, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
node: relocation error: node: symbol -Emcmp, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
node: relocation error: node: symbol -Emcmp, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference
node: relocation error: node: symbol -Emcmp, version GLIBC_2.2.5 not defined in file libc.so.6 with link time reference                                      |Job for pm2-zstack.service failed because the control process exited with error code. See "systemctl status pm2-zstack.service" and "journalctl -xe" for details.                                                                           fail to start UI server on the localhost. Use zstack-ctl start_ui to restart it. zstack UI log could be found in /usr/local/zstack/zstack-ui/logs/zstack-ui-server.log

执行命令“systemctl status pm2-zstack.service”返回信息：

● pm2-zstack.service - PM2 process manager
   Loaded: loaded (/etc/systemd/system/pm2-zstack.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2023-06-20 10:42:25 CST; 4min 0s ago
     Docs: https://pm2.keymetrics.io/
  Process: 43525 ExecStart=/usr/local/zstack/zstack-ui/node_modules/pm2/bin/pm2 resurrect (code=exited, status=127)

Jun 20 10:42:25 192-168-1-70 systemd[1]: Failed to start PM2 process manager.
Jun 20 10:42:25 192-168-1-70 systemd[1]: Unit pm2-zstack.service entered fa....
Jun 20 10:42:25 192-168-1-70 systemd[1]: pm2-zstack.service failed.
Jun 20 10:42:25 192-168-1-70 systemd[1]: pm2-zstack.service holdoff time ov....
Jun 20 10:42:25 192-168-1-70 systemd[1]: Stopped PM2 process manager.
Jun 20 10:42:25 192-168-1-70 systemd[1]: start request repeated too quickly...e
Jun 20 10:42:25 192-168-1-70 systemd[1]: Failed to start PM2 process manager.
Jun 20 10:42:25 192-168-1-70 systemd[1]: Unit pm2-zstack.service entered fa....
Jun 20 10:42:25 192-168-1-70 systemd[1]: pm2-zstack.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by sinbargit** [comment]
请先在命令行输入 ：` ps aux | grep pm2。`  如果发现有许多的pm2进程，就` ps aux | grep pm2 |xargs kill -9` 杀掉他们。

**Comment by admin-ping** [comment]
查找并未发现存在pm2进程

**Comment by sinbargit** [comment]
ps aux | grep node 会出现很多进程么

**Comment by admin-ping** [comment]
这是具体返回结果
[root@192-168-1-70 ~]# ps aux | grep pm2
root     26945  0.0  0.0 112708   976 pts/2    S+   14:41   0:00 grep --color=auto pm2

**Comment by sinbargit** [comment]
如果`ps aux | grep node` 有进程，就杀掉他们。 不管有没有都可以尝试运行下`systemctl start pm2-zstack`

**Comment by sinbargit** [comment]
如果`ps aux | grep node` 有进程，就杀掉他们。 不管有没有都可以尝试运行下`systemctl start pm2-zstack`

**Comment by admin-ping** [comment]
[root@192-168-1-70 ~]# systemctl start pm2-zstack
Job for pm2-zstack.service failed because the control process exited with error code. See "systemctl status pm2-zstack.service" and "journalctl -xe" for details.

**Comment by sinbargit** [comment]
`/usr/local/zstack/zstack-ui/node_modules/pm2/bin/pm2 resurrect`

**Comment by sinbargit** [comment]
这个只要是14.15.1版本或者以上的nodejs都可以的。 可以使用yum install 安装，也可以网上下载安装包安装，或者自己编译构建安装都可以。

**Comment by sinbargit** [comment]
这个只要是14.15.1版本或者以上的nodejs都可以的。 可以使用yum install 安装，也可以网上下载安装包安装，或者自己编译构建安装都可以。

**Comment by admin-ping** [comment]
整合解决方案：

**Comment by admin-ping** [comment]
整合解决方案：

运行一下命令
`yum -y remove nodejs`
`yum -y install nodejs`
`zstack-ctl stop`
`zstack-ctl start`
成功解决
