### ISSUE TITLE
云主机无法启动！！！！

### ISSUE THREAD

**Issue by chengzx98** [zstackio/zstack#1344]
![image](https://github.com/zstackio/zstack/assets/108660896/639f503c-82d5-4cb5-8bab-351b187f4f42)
![image](https://github.com/zstackio/zstack/assets/108660896/0bcb74d3-3baf-44b9-b58e-45ea96363bc9)
我今天发现云主机启动失败，我并没有修改任何配置，运行的是zstack v3.10.0。

**Comment by AlanJager** [comment]
@chengzx98 这个报错看起来是你的host上iptables命令找不到了

你可以ssh到你的物理机上，执行一下 `iptables -L` 试一下吗？ssh的时候使用添加host使用的用户和密码就行

**Comment by chengzx98** [comment]
ssh上后，发现物理机上面没有iptables命令，我发现另外两台同版本的v3.10版本的出现同样的问题，不知道问题出在哪。
![image](https://github.com/zstackio/zstack/assets/108660896/d4dd53fd-d15e-4570-b329-ed06ec8d1302)

**Comment by AlanJager** [comment]
> ssh上后，发现物理机上面没有iptables命令，我发现另外两台同版本的v3.10版本的出现同样的问题，不知道问题出在哪。 ![image](https://user-images.githubusercontent.com/108660896/283286849-d4dd53fd-d15e-4570-b329-ed06ec8d1302.png)

这个看起来只和系统有关。

可以通过：`rpm -qa | grep iptables` 这个确认一下对应的rpm是否正确安装。如果没有安装，通过`yum install iptables`安装即可

另外可以看一下 `sudo iptables -L` 是否可以正常使用。

**Comment by chengzx98** [comment]
> > ssh之后，发现物理机上面没有iptables命令，我发现另外同版本的v3.10版本的出现了同样的问题，不知道问题出在哪。![图像](https://user-images.githubusercontent.com/108660896/283286849-d4dd53fd-d15e-4570-b329-ed06ec8d1302.png)
> 
> 这个外观只和系统有关。
> 
> 可以通过：`rpm -qa | grep iptables`这个确认一下对应的rpm是否正确安装。如果没有安装，通过`yum install iptables`安装即可
> 
> 另外可以看看`sudo iptables -L`是否可以正常使用。

已经解决，谢谢你的回复！

**Comment by AlanJager** [comment]
@chengzx98 你是如何解决这个问题的，方便分享一下原因和处理方法么？

**Comment by chengzx98** [comment]
排查发现可能是我的软件包出现了问题，我重新安装iptables解决。
yum -y reinstall iptables
