### ISSUE TITLE
ZStack 4.8.0 创建虚拟机指定本地存储提示 所需的物理机无法满足条件和条件

### ISSUE THREAD

**Issue by ztj1993** [zstackio/zstack#1351]
版本：ZStack 4.8.0
本地存储：正常，能创建卷
Ceph 存储：正常，能创建卷

当创建虚拟机指定本地存储时，会提示：
`所需的物理机[uuid：89e9467b7d4f4fc989011783fe76737e]无法满足条件[状态：Enabled，状态：Connected，大小>10,737,418,240字节]，或者不属于满足条件[状态：Enabled，状态：Connected]的本地主存储，或者其群集未连接到任何本地主存储', 'location': 'VmInstanceManagerImpl.java: instantiate-new-created-vmInstance (location:4/4)', 'cause': {'code': 'SYS.1006', 'description': 'An operation failed', 'details': '所需的物理机[uuid：89e9467b7d4f4fc989011783fe76737e]无法满足条件[状态：Enabled，状态：Connected，大小>10,737,418,240字节]，或者不属于满足条件[状态：Enabled，状态：Connected]的本地主存储，或者其群集未连接到任何本地主存储`

请求参数：
`POST http://192.168.13.10:8080/zstack/v1/vm-instances () {'json_body': {'params': {'name': 'CLOUD_SYNC_GATEWAY-2024-0605-091142', 'zoneUuid': 'dc26a76be8104714bfcf248a1ce7856a', 'instanceOfferingUuid': 'd5d5e32ba0ab48fb98536a7e4392a0e5', 'l3NetworkUuids': ['b392827acafb419bbdd38fa64cc4bc53'], 'strategy': 'InstantStart', 'hostUuid': '89e9467b7d4f4fc989011783fe76737e', 'primaryStorageUuidForRootVolume': 'c0f3d11cc52c42258465eac458e54de3', 'imageUuid': 'd5a2c95972e64d29a2c9c0110718f5fd'}}} {'Content-Type': 'application/x-www-form-urlencoded', 'Authorization': 'ZStack 9Nm6cGhpUsv7rWDjT0UJ:Va+c6j5dqG+4duzdnVtYL2iqluQ=', 'Date': 'Wed, 05 Jun 2024 09:11:43 CST'}`

请问是版本 BUG 吗？需要升级解决还是我传递的参数错误？

**Comment by AlanJager** [comment]
@ztj1993 我检查了一下相关的已知问题，没有发现本地存储上存在类似的bug。
为了检查一下这个错误的具体原因，需要分析一下相关日志，希望能够提供
如下形式和这个请求相关的api日志便于我们进一步分析，这里截取一部分
`2024-06-05 03:39:01,458 TRACE [CloudBusImpl3] {api=c0e14f05c89e452c8d4846c5c2c079c6}` 
日志路径可以通过 `zstack-ctl status` 的 `log file:` 信息获取，一般形式如下：
`log file: /usr/local/zstack/apache-tomcat/logs/management-server.log`

具体的apiid需要根据你的请求查找一下：
根据apiid `grep c0e14f05c89e452c8d4846c5c2c079c6 /usr/local/zstack/apache-tomcat/logs/management-server.log` 把关联的日志以附件形式提交一下么

**Comment by ztj1993** [comment]
[test.log](https://github.com/user-attachments/files/15572319/test.log)
我重新做了一次请求，获取到的日志在附件中。

**Comment by ztj1993** [comment]
@AlanJager 我本地主存储的磁盘容量 > 14TB，指定主存储时，指定 Ceph 存储没有问题，指定本地存储就报这个错。

**Comment by ztj1993** [comment]
@AlanJager 是不是因为我镜像服务器放在 Ceph 中导致的？

**Comment by AlanJager** [comment]
`2024-06-05 10:17:05,535 DEBUG [LocalStorageMainAllocatorFlow] {api=2fe70d7040cf4f2cb6370e055bf269cb} (zs-thread-54) the primary storage[name:LocalStorage-2, uuid:c0f3d11cc52c42258465eac458e54de3, type:LocalStorage] is not in possible primary storage types[[Ceph]], remove it`
看错误是这个原因，如果是镜像在ceph的情况下，需要ps也需要指定ceph存储。假设你需要使用本地存储可以在对应的区域（zone）添加一个imagestore类型的镜像服务器并指定对应的镜像

我觉得这个可能是在最近重构存储+物理机分配逻辑后引入的问题，通常这样的错误应该在更早的阶段被发现。

**Comment by ztj1993** [comment]
这个问题涉及到 ImageStore 镜像服务器，Ceph 镜像服务器，以及使用 LocalStorage，NFS，Ceph 等多种存储的交叉测试。

我最近的测试中只使用了 Ceph 和 LocalStorage。

一会要是方便，我试下 NFS 存储。

**Comment by AlanJager** [comment]
> 这个问题涉及到 ImageStore 镜像服务器，Ceph 镜像服务器，以及使用 LocalStorage，NFS，Ceph 等多种存储的交叉测试。
> 
> 我最近的测试中只使用了 Ceph 和 LocalStorage。
> 
> 一会要是方便，我试下 NFS 存储。

支持关系参照，保存在 springConfig/HostAllocatorManager.xml 中
```
    <util:list id="SftpBackupStorageMetric">
        <value>NFS</value>
        <value>SharedMountPoint</value>
        <value>LocalStorage</value>
    </util:list>

    <util:list id="ImageStoreBackupStorageMetric">
        <value>NFS</value>
        <value>SharedMountPoint</value>
        <value>LocalStorage</value>
        <value>Ceph</value>
    </util:list>

    <util:list id="CephMetric">
        <value>Ceph</value>
    </util:list>

    <util:list id="VCenterMetric">
        <value>VCenter</value>
    </util:list>
```

**Comment by ztj1993** [comment]
@AlanJager 好的，谢谢！
