### ISSUE TITLE
社区单机版4.2.28 离线升级到4.4.64出现异常！

### ISSUE THREAD

**Issue by chengzx98** [zstackio/zstack#1352]
升级操作：
1.在官网下载镜像ZStack-Cloud-x86_64-DVD-4.4.64-c76.iso
2.备份数据库跟升级脚本。
3.离线升级。zstack-upgrade ZStack-Cloud-x86_64-DVD-4.4.64-c76.iso
4.升级完成。
![image](https://github.com/zstackio/zstack/assets/108660896/eba98ee3-3c59-43a0-b4e7-fd735aac8ef9)
![image](https://github.com/zstackio/zstack/assets/108660896/73923c15-4fc2-4675-9664-423fdcc01e66)

出现的异常：
1.打开控制台，发现云主机启用状态为未知，然后去排查发现硬件设备集群跟物理机都没有连接上，一直处于连接中，
![image](https://github.com/zstackio/zstack/assets/108660896/79f69ed8-fc6c-4a9c-a6db-edb0dccddfd6)
![image](https://github.com/zstackio/zstack/assets/108660896/6a80bf4f-fca4-4848-a098-78d63c344048)
尝试的操作：
重启管理节点。zstack-ctl stop &zstack-ctl start ,并没有发生改变

我需要帮助，期望恢复正常。

**Comment by chengzx98** [comment]
是不是丢失了什么，我点击创建集群，是空白的
![image](https://github.com/zstackio/zstack/assets/108660896/3584190a-e311-4c85-a84b-4185a2d733dd)

**Comment by MatheMatrix** [comment]
请确认原系统版本和升级系统的版本一致，并上传管理节点日志看下

**Comment by chengzx98** [comment]
已经解决了，物理机ssh没连接上，

**Comment by chengzx98** [comment]
给其他人建议，升级后，浏览器缓存要清理一下
