### ISSUE TITLE
如何能通过 API 接口获取 UI 控制台地址

### ISSUE THREAD

**Issue by ztj1993** [zstackio/zstack#1353]
我使用下面的 API 获取了云主机控制台地址，但是还需要 UI 的地址才能打开云控制台，我如何获取 UI 地址。

https://www.zstack.io/help/dev_manual/dev_guide/v5/9.4.html

http://172.20.19.60:5000/novnc?host=172.20.16.95&port=4900&token=cbc32f54862f4a5296b97a1302975fb9_f601842905994688a3cf7100e8d54b23_1666013527.59

这个连接中的 ?host=172.20.16.95&port=4900&token=cbc32f54862f4a5296b97a1302975fb9_f601842905994688a3cf7100e8d54b23_1666013527.59 可以通过接口获取，但是 http://172.20.19.60:5000/novnc 如何通过接口来获取？

我未在文档中找到方法。

**Comment by MatheMatrix** [comment]
ui 的地址取决于网络配置，比如反向代理、负载均衡，没法从后端的 api 获取，建议先设个变量之类的存一下吧，或者直接用后端 api 的 ip

**Comment by ztj1993** [comment]
好吧
